#!/bin/sh

set -e

installdir=/usr/local/bin

for bin in elm elm-compiler elm-get elm-reactor elm-repl elm-doc elm-server
do
	if [ -f $installdir/$bin ]; then
		sudo rm -f $installdir/$bin
	fi
	if [ -f $installdir/$bin-unwrapped ]; then
		sudo rm -f $installdir/$bin-unwrapped
	fi
done

sharedir=/usr/local/share/elm
sudo rm -rf $sharedir
